export const categories = [
  'Accounting',
  'Advertising & Marketing',
  'Banking & Finance',
  'Business',
  'Business - Female Specific',
  'Business Appointments',
  'Business Management',
  'Business Travel',
  'Careers',
  'Consumer Issues',
  'Economics',
  'Entrepreneurship',
  'Equity - Private & Public',
  'Franchising',
  'Heavy Duty Transport & Cranes',
  'Innovation & Startup Policy',
  'Insurance',
  'Media & PR Trade',
  'Mining & Resources',
  'Money & Personal Finance',
  'Nonprofit, Charities, Fundraising',
  'Politics & Government',
  'Politics & Government - Federal',
  'Politics & Government - Local',
  'Politics & Government - State',
  'Property - Commercial',
  'Property - Residential',
  'Search Engine Marketing Industry',
  'Statistics',
  'Superannuation',
  'Workplace Relations',
];
